"""init

Revision ID: 06582ce20ec1
Revises: c1ed27a938bd
Create Date: 2026-01-21 14:03:43.017564

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '06582ce20ec1'
down_revision: Union[str, Sequence[str], None] = 'c1ed27a938bd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('group_name_key'), 'group', type_='unique')
    op.drop_constraint(op.f('oasis_entity_name_key'), 'oasis_entity', type_='unique')
    op.drop_constraint(op.f('oasis_network_name_key'), 'oasis_network', type_='unique')
    op.drop_constraint(op.f('oasis_node_name_key'), 'oasis_node', type_='unique')
    op.drop_constraint(op.f('oasis_nodetype_name_key'), 'oasis_nodetype', type_='unique')
    op.drop_constraint(op.f('oasis_paratime_config_name_key'), 'oasis_paratime_config', type_='unique')
    op.drop_constraint(op.f('organisation_name_key'), 'organisation', type_='unique')
    op.drop_constraint(op.f('user_name_key'), 'user', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(op.f('user_name_key'), 'user', ['name'], postgresql_nulls_not_distinct=False)
    op.create_unique_constraint(op.f('organisation_name_key'), 'organisation', ['name'], postgresql_nulls_not_distinct=False)
    op.create_unique_constraint(op.f('oasis_paratime_config_name_key'), 'oasis_paratime_config', ['name'], postgresql_nulls_not_distinct=False)
    op.create_unique_constraint(op.f('oasis_nodetype_name_key'), 'oasis_nodetype', ['name'], postgresql_nulls_not_distinct=False)
    op.create_unique_constraint(op.f('oasis_node_name_key'), 'oasis_node', ['name'], postgresql_nulls_not_distinct=False)
    op.create_unique_constraint(op.f('oasis_network_name_key'), 'oasis_network', ['name'], postgresql_nulls_not_distinct=False)
    op.create_unique_constraint(op.f('oasis_entity_name_key'), 'oasis_entity', ['name'], postgresql_nulls_not_distinct=False)
    op.create_unique_constraint(op.f('group_name_key'), 'group', ['name'], postgresql_nulls_not_distinct=False)
    # ### end Alembic commands ###
