"""add functions

Revision ID: 20260121_02_rls
Revises: 20260121_01_rls
Create Date: 2026-01-21 19:44:17.245852

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from alembic_utils.pg_function import PGFunction
from sqlalchemy import text as sql_text

# revision identifiers, used by Alembic.
revision: str = "20260121_02_rls"
down_revision: Union[str, Sequence[str], None] = "20260121_01_rls"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    public_list_public_tables = PGFunction(
        schema="public",
        signature="list_public_tables()",
        definition="returns table (\n  table_name text\n)\nlanguage sql\nsecurity definer\nset search_path = public\nas $$\n  select tablename::text\n  from pg_catalog.pg_tables\n  where schemaname = 'public'\n  order by tablename;\n$$",
    )
    op.create_entity(public_list_public_tables)

    public_current_user_id = PGFunction(
        schema="public",
        signature="current_user_id()",
        definition='returns integer\nlanguage sql\nstable\nsecurity definer\nset search_path = public\nas $$\n  select u.id\n  from public."user" u\n  where u.auth_user_id = auth.uid()\n$$',
    )
    op.create_entity(public_current_user_id)

    public_is_org_member = PGFunction(
        schema="public",
        signature="is_org_member(p_org_id integer)",
        definition='returns boolean\nlanguage sql\nstable\nsecurity definer\nset search_path = public\nas $$\n  select exists (\n    select 1\n    from public.user_group_association uga\n    join public."group" g on g.id = uga.group_id\n    where uga.user_id = public.current_user_id()\n      and g.organisation_id = p_org_id\n  );\n$$',
    )
    op.create_entity(public_is_org_member)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    public_list_public_tables = PGFunction(
        schema="public",
        signature="list_public_tables()",
        definition="returns table (\n  table_name text\n)\nlanguage sql\nsecurity definer\nset search_path = public\nas $$\n  select tablename::text\n  from pg_catalog.pg_tables\n  where schemaname = 'public'\n  order by tablename;\n$$",
    )
    op.drop_entity(public_list_public_tables)

    public_is_org_member = PGFunction(
        schema="public",
        signature="is_org_member(p_org_id integer)",
        definition='returns boolean\nlanguage sql\nstable\nsecurity definer\nset search_path = public\nas $$\n  select exists (\n    select 1\n    from public.user_group_association uga\n    join public."group" g on g.id = uga.group_id\n    where uga.user_id = public.current_user_id()\n      and g.organisation_id = p_org_id\n  );\n$$',
    )
    op.drop_entity(public_is_org_member)

    public_current_user_id = PGFunction(
        schema="public",
        signature="current_user_id()",
        definition='returns integer\nlanguage sql\nstable\nsecurity definer\nset search_path = public\nas $$\n  select u.id\n  from public."user" u\n  where u.auth_user_id = auth.uid()\n$$',
    )
    op.drop_entity(public_current_user_id)

    # ### end Alembic commands ###
