"""add_policy

Revision ID: 20260121_03_rls
Revises: 20260121_02_rls
Create Date: 2026-01-21 21:34:12.332463

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from alembic_utils.pg_policy import PGPolicy
from sqlalchemy import text as sql_text

# revision identifiers, used by Alembic.
revision: str = "20260121_03_rls"
down_revision: Union[str, Sequence[str], None] = "20260121_02_rls"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    public_server_server_select_org_member = PGPolicy(
        schema="public",
        signature="server_select_org_member",
        on_entity="public.server",
        definition="AS PERMISSIVE\n        FOR SELECT\n        TO authenticated\n        USING (public.is_org_member(organisation_id))",
    )
    op.create_entity(public_server_server_select_org_member)

    # ### end Alembic commands ###
    op.execute("ALTER TABLE public.server ENABLE ROW LEVEL SECURITY;")


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    public_server_server_select_org_member = PGPolicy(
        schema="public",
        signature="server_select_org_member",
        on_entity="public.server",
        definition="AS PERMISSIVE\n        FOR SELECT\n        TO authenticated\n        USING (public.is_org_member(organisation_id))",
    )
    op.drop_entity(public_server_server_select_org_member)

    # ### end Alembic commands ###
