"""server_status2

Revision ID: 39abc9022b13
Revises: b5f75525bb86
Create Date: 2026-03-06 23:17:37.956826

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from alembic_utils.pg_policy import PGPolicy
from sqlalchemy import text as sql_text

# revision identifiers, used by Alembic.
revision: str = '39abc9022b13'
down_revision: Union[str, Sequence[str], None] = 'b5f75525bb86'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    public_server_status_server_status_select_org_member = PGPolicy(
        schema="public",
        signature="server_status_select_org_member",
        on_entity="public.server_status",
        definition='AS PERMISSIVE\n        FOR SELECT\n        TO authenticated\n        USING (public.is_server_member(server_id))'
    )
    op.create_entity(public_server_status_server_status_select_org_member)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    public_server_status_server_status_select_org_member = PGPolicy(
        schema="public",
        signature="server_status_select_org_member",
        on_entity="public.server_status",
        definition='AS PERMISSIVE\n        FOR SELECT\n        TO authenticated\n        USING (public.is_server_member(server_id))'
    )
    op.drop_entity(public_server_status_server_status_select_org_member)

    # ### end Alembic commands ###
