"""functions

Revision ID: 3
Revises: 2
Create Date: 2026-02-27 23:36:32.046029

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from alembic_utils.pg_policy import PGPolicy
from sqlalchemy import text as sql_text

# revision identifiers, used by Alembic.
revision: str = '3'
down_revision: Union[str, Sequence[str], None] = '2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    public_user_user_select = PGPolicy(
        schema="public",
        signature="user_select",
        on_entity="public.user",
        definition='AS PERMISSIVE\n        FOR SELECT\n        TO authenticated\n        USING (auth.uid() = auth_user_id)'
    )
    op.replace_entity(public_user_user_select)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    public_user_user_select = PGPolicy(
        schema="public",
        signature="user_select",
        on_entity="public.user",
        definition='as PERMISSIVE for SELECT to authenticated using (is_user())'
    )
    op.replace_entity(public_user_user_select)
    # ### end Alembic commands ###
