"""server_status

Revision ID: b5f75525bb86
Revises: 6f1d2c9a4b7e
Create Date: 2026-03-06 23:01:51.327550

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b5f75525bb86'
down_revision: Union[str, Sequence[str], None] = '6f1d2c9a4b7e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('server_status',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('server_id', sa.Integer(), nullable=False),
    sa.Column('time_create', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('time_updated', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('uptime', sa.String(), nullable=True),
    sa.Column('load_avg_1m', sa.String(), nullable=True),
    sa.Column('load_avg_5m', sa.String(), nullable=True),
    sa.Column('load_avg_15m', sa.String(), nullable=True),
    sa.Column('memory_total_mb', sa.String(), nullable=True),
    sa.Column('memory_used_mb', sa.String(), nullable=True),
    sa.Column('memory_free_mb', sa.String(), nullable=True),
    sa.Column('memory_shared_mb', sa.String(), nullable=True),
    sa.Column('memory_buff_cache_mb', sa.String(), nullable=True),
    sa.Column('memory_available_mb', sa.String(), nullable=True),
    sa.Column('swap_total_mb', sa.String(), nullable=True),
    sa.Column('swap_used_mb', sa.String(), nullable=True),
    sa.Column('swap_free_mb', sa.String(), nullable=True),
    sa.Column('health_reachable', sa.String(), nullable=True),
    sa.Column('health_service_active', sa.String(), nullable=True),
    sa.Column('health_service_status_ok', sa.String(), nullable=True),
    sa.Column('collected_at', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['server_id'], ['server.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('server_status')
    # ### end Alembic commands ###
