"""init

Revision ID: c1ed27a938bd
Revises: 49f40bdad1d2
Create Date: 2026-01-21 13:41:28.090879

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c1ed27a938bd'
down_revision: Union[str, Sequence[str], None] = '49f40bdad1d2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('server_name_key'), 'server', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(op.f('server_name_key'), 'server', ['name'], postgresql_nulls_not_distinct=False)
    # ### end Alembic commands ###
