"""init

Revision ID: c315a1d488f9
Revises: e0c2a1c2633d
Create Date: 2026-01-21 15:39:37.579245

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c315a1d488f9'
down_revision: Union[str, Sequence[str], None] = 'e0c2a1c2633d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('entrypoint_server_id_fkey'), 'entrypoint', type_='foreignkey')
    op.create_foreign_key(None, 'entrypoint', 'server', ['server_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'entrypoint', type_='foreignkey')
    op.create_foreign_key(op.f('entrypoint_server_id_fkey'), 'entrypoint', 'server', ['server_id'], ['id'])
    # ### end Alembic commands ###
