"""init

Revision ID: de2259c2edb5
Revises: c315a1d488f9
Create Date: 2026-01-21 15:42:45.966251

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'de2259c2edb5'
down_revision: Union[str, Sequence[str], None] = 'c315a1d488f9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('oasis_node_entrypoint_admin_id_fkey'), 'oasis_node', type_='foreignkey')
    op.drop_constraint(op.f('oasis_node_entrypoint_id_fkey'), 'oasis_node', type_='foreignkey')
    op.create_foreign_key(None, 'oasis_node', 'entrypoint', ['entrypoint_admin_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(None, 'oasis_node', 'entrypoint', ['entrypoint_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'oasis_node', type_='foreignkey')
    op.drop_constraint(None, 'oasis_node', type_='foreignkey')
    op.create_foreign_key(op.f('oasis_node_entrypoint_id_fkey'), 'oasis_node', 'entrypoint', ['entrypoint_id'], ['id'])
    op.create_foreign_key(op.f('oasis_node_entrypoint_admin_id_fkey'), 'oasis_node', 'entrypoint', ['entrypoint_admin_id'], ['id'])
    # ### end Alembic commands ###
